version: "3.8"
services:
  # 主节点服务
  timescaledb-master:
    image: timescale/timescaledb:2.17.2-pg16
    environment:
      - POSTGRES_PASSWORD=PH0BGhrGW9NUMvHCnaGX
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - TIMESCALEDB_TELEMETRY=off  # 关闭 Telemetry（可选）
         # 添加以下主库复制配置
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=replicator
      - POSTGRESQL_REPLICATION_PASSWORD=replpass123
      # 重要：设置复制参数
      - POSTGRESQL_WAL_LEVEL=replica
      - POSTGRESQL_MAX_WAL_SENDERS=5
      - POSTGRESQL_MAX_REPLICATION_SLOTS=10
      - POSTGRESQL_ENABLE_REPLICATION=true
      - POSTGRESQL_SYNCHRONOUS_COMMIT=on
      - POSTGRESQL_SYNCHRONOUS_REPLICA_MODE=first
    command: >
      -c wal_level=replica
      -c max_wal_senders=10
      -c max_replication_slots=10
      -c synchronous_commit=on
      -c listen_addresses='*'
      -c hot_standby=on
    ports:
      - 5432:5432
    volumes:
      - timescale-data-master:/var/lib/postgresql/data
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.db.role == manager]  # 仅在 manager 节点上运行主节点
    networks:
      - postgres_network

  # 从节点服务
  timescaledb-replica:
    image: timescale/timescaledb:2.17.2-pg16
    environment:
      - POSTGRES_PASSWORD=TH0BGhrGW9NUMvHCnaGY
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      # 修改从库复制配置
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=replicator
      - POSTGRESQL_REPLICATION_PASSWORD=replpass123
      - POSTGRESQL_MASTER_HOST=timescaledb-master
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      # 添加以下配置
      - POSTGRESQL_MASTER_DB=postgres
      - POSTGRESQL_MASTER_USER=replicator
      - POSTGRESQL_MASTER_PASSWORD=replpass123
      - POSTGRESQL_PASSWORD=TH0BGhrGW9NUMvHCnaGY
      - POSTGRESQL_ENABLE_REPLICATION=true
    command: >
      -c wal_level=replica
      -c hot_standby=on
      -c max_wal_senders=10
      -c max_replication_slots=10
      -c hot_standby_feedback=on
      -c primary_conninfo='host=timescaledb-master port=5432 user=replicator password=replpass123'
    ports:
      - 5433:5432
    volumes:
      - timescale-data-replica:/var/lib/postgresql/data
    deploy:
      replicas: 1  # 启动两个从节点
      placement:
        constraints: [node.labels.db.role == worker]  # 仅在 worker 节点上运行从节点
    networks:
      - postgres_network

volumes:
  timescale-data-master:
    driver: local
  timescale-data-replica:
    driver: local

# 添加网络配置
networks:
  postgres_network:
    driver: overlay
    attachable: true