version: "3.8"
services:
  timescaledb-master:
    image: timescale/timescaledb:2.17.2-pg16
    environment:
      - POSTGRES_PASSWORD=PH0BGhrGW9NUMvHCnaGX
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - TIMESCALEDB_TELEMETRY=off
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=replicator
      - POSTGRESQL_REPLICATION_PASSWORD=replpass123
    command: >
      -c wal_level=replica
      -c max_wal_senders=10
      -c max_replication_slots=10
      -c synchronous_commit=on
      -c listen_addresses='*'
    ports:
      - 5432:5432
    volumes:
      - timescale-data-manager:/var/lib/postgresql/data
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.db.role == manager]

  timescaledb-replica:
    image: timescale/timescaledb:2.17.2-pg16
    environment:
      - POSTGRES_PASSWORD=TH0BGhrGW9NUMvHCnaGY
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=replicator
      - POSTGRESQL_REPLICATION_PASSWORD=replpass123
      - POSTGRESQL_MASTER_HOST=timescaledb-master
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - POSTGRESQL_MASTER_DB=postgres
    command: >
      -c wal_level=replica
      -c hot_standby=on
      -c max_wal_senders=10
      -c max_replication_slots=10
      -c hot_standby_feedback=on
    ports:
      - 5433:5432
    volumes:
      - timescale-data-slaver:/var/lib/postgresql/data
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.db.role == worker]
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "timescaledb-master", "-p", "5432"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  timescale-data-manager:
    driver: local
  timescale-data-slaver:
    driver: local

networks:
  timescale-net:
    driver: overlay