version: '3.8'
services:
  openproject:
    image: openproject/openproject:15
    container_name: openproject
    restart: unless-stopped
    ports:
      - "8098:80"
    environment:
      - OPENPROJECT_SECRET_KEY_BASE=secret
      - OPENPROJECT_HOST__NAME=localhost:8098
      - OPENPROJECT_HTTPS=false
      - OPENPROJECT_DEFAULT__LANGUAGE=en
