version: '3.8'

services:
  {{.Values.APP_NAME}}:
    image: {{ .Values.APP_IMAGE }}:{{ .Values.APP_VERSION }}
    labels:
      - "io.docker/group={{.Values.APP_GROUP}}"
      - "io.docker/app={{.Values.APP_NAME}}"
      - "io.docker/version={{.Values.APP_VERSION}}"
      - "io.docker/stack={{.Values.APP_STACK}}"
      - "io.docker/env={{.Values.ENV_NAME}}"
      - "io.docker/type={{.Values.APP_TYPE}}"
    environment:
      - SPRING_PROFILES_ACTIVE={{.Values.ENV_NAME}}
    ports:
      {{- if .Values.NODE_PORT }}
      - "{{.Values.NODE_PORT}}:{{.Values.CONTAINER_PORT}}"
      {{- else }}
      - "{{.Values.CONTAINER_PORT}}"
      {{- end}}
    networks:
      - pg_default
      - redis_default
      - mysql_default
      - mongo_default
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/actuator/health"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 4g
          cpus: '2'
      affinity:
        - "affinity: !container: io.docker/group"
        - "affinity: !container: io.docker/app"
        - "affinity: !container: io.docker/version"
        - "affinity: !container: io.docker/stack"
        - "affinity: !container: io.docker/env"
        - "affinity: !container: io.docker/type"

networks:
  pg_default:
    external: true
  redis_default:
    external: true
  mysql_default:
    external: true
  mongo_default:
    external: true

