version: "3.8"
services:
  nacos:
    image: registry.local:5000/nacos/nacos-server:v2.4.3
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=mysql-master
      - MYSQL_SERVICE_DB_NAME=nacos
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=nacos
      - MYSQL_SERVICE_PASSWORD=2psNHVApAH3efHc2srMk
      - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      - NACOS_AUTH_IDENTITY_KEY=2222
      - NACOS_AUTH_IDENTITY_VALUE=2xxx
      - NACOS_AUTH_TOKEN=SecretKey012345678901234567890123456789012345678901234567890123456789
    volumes:
      - nacos_data:/home/nacos/logs
    ports:
      - "8848:8848"
      - "9848:9848"
    networks:
      - mysql_default
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.nacos == manager

networks:
  mysql_default:
    external: true

volumes:
  nacos_data:
    driver: local
