# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - "alertmanager:9093"

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
   - "rule.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "postgresql"
    static_configs:
      - targets: ["postgresql-exporter:9187"]
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: 'node'
    static_configs:
      - targets: ['node_exporter:9100']
  - job_name: 'xzai'
    static_configs:
      - targets: ['192.168.1.102:8091']

  - job_name: 'node-exporter'
    docker_sd_configs:
      - host: "unix:///var/run/docker.sock"
        filters:
          - name: 'label'
            values: ['com.docker.swarm.service.name=node-exporter']
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        target_label: 'instance'
        regex: '/(.*)'
        replacement: '${1}'