global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"

rule_files:
  - "rule.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "redis-primary"
    static_configs:
      - targets: ["redis-exporters_redis-primary-exporter:9121"]
        labels:
          instance: "redis-primary"

  - job_name: "redis-secondary"
    static_configs:
      - targets: ["redis-exporters_redis-secondary-exporter:9121"]
        labels:
          instance: "redis-secondary"

  - job_name: "postgres-exporters"
    static_configs:
      - targets: ["postgres-primary-exporter:9187", "postgres-secondary-exporter:9187"]

  - job_name: "cadvisor-exporters"
    static_configs:
      - targets: ["cadvisor-1:8080", "cadvisor-2:8080", "cadvisor-3:8080"]

  - job_name: "node-exporters"
    static_configs:
      - targets: ["node-exporter-1:9100", "node-exporter-2:9100", "node-exporter-3:9100"]

  - job_name: "tjxz-backend-admin_app"
    metrics_path: "/actuator/prometheus"
    scheme: "http"
    static_configs:
      - targets: ["tjxz-backend-admin_tjxz-backend-admin_app:80"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __host__
        replacement: "backend" 

  - job_name: "tjxz-gateway_app"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["192.168.1.102:8089"]

  - job_name: "xzai-exporters"
    static_configs:
      - targets: ["192.168.1.102:9102"]

  - job_name: "xzai"
    static_configs:
      - targets: ["192.168.1.102:8091"]
        labels:
          app: "xzai"
          env: "production"
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        target_label: "instance"
        regex: "/(.*)"
        replacement: "${1}"
      - source_labels: [__meta_docker_service_name]
        target_label: "service"